config/routes.rb
MyBallot::Application.routes.draw do
  
  resources :comments

  resources :positions

  resources :users

  get "/login" => 'Sessions#new', :as => 'login'

  post "/sessions" => 'Sessions#create'

  get "/logout" => 'Sessions#destroy', :as => 'logout'

  root :to => 'Pages#home'
  
  get "/" => 'Pages#home', :as => 'home'

  post "/ballot" => 'Pages#createballot'

  get "/ballot" => 'Pages#ballot', :as => 'ballot'

  get "/candidate" => 'Pages#candidatebio', :as => 'candidatebio'

  get "/resources" => 'Pages#resources', :as => 'resources'

  get "/about" => 'Pages#about', :as => 'about'

  get "/users/update_votes"  => 'Users#votes', :as => 'vote'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBallot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <meta name = "viewport" content = "width = device-width">
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
</head>

<body>
	<nav>
		<ul>
			<% if current_user %>
				<li><%=	link_to "My Profile", user_url(current_user)%></li>
				<li><%=	link_to "Resources", resources_url%></li>
				<li><%=	link_to "Log out", logout_url%></li>
			<% else %> 
				<li><%=	link_to "Sign up", new_user_url%></li>
				<li><%=	link_to "Resources", resources_url%></li>
				<li><%=	link_to "Log in", login_url %></li>
				
			<% end %>
		</ul>
	</nav>

<%= yield %>

	<footer>
		<ul>
			<li class="copyright">&copy; 2012 MyBallot</li>
			<li><%=	link_to "About Us", about_url %></li>
			<li><%=	link_to "Home", home_url %></li>
		</ul>
	</footer>

</body>
</html>